##############################################################################
#   
#  Configuration for the MkDocs-base site.
#
#  This file is part of XAD, a comprehensive C++ library for
#  automatic differentiation.
#
#  Copyright (C) 2010-2023 Xcelerit Computing Ltd.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   
##############################################################################

# Project information
site_name: XAD
site_url: https://auto-differentiation.github.io
site_author: Xcelerit
site_description: >-
  XAD is a comprehensive open-source C++ library for automatic differentiation by Xcelerit. 
  It targets production-quality code at any scale, striving for both ease of use and 
  high performance.


# Repository
repo_url: "https://github.com/auto-differentiation/XAD/"
repo_name: XAD

# Copyright + cookie settings in footer
copyright: >
  Copyright &copy; 2010-2023, Xcelerit Computing Ltd |
  <a href="#__consent">Cookie settings</a>

# Configuration
theme:
  name: material
  custom_dir: docs/.overrides
  logo: images/logo.svg
  palette:
    - scheme: default
      primary: grey
      media: "(prefers-color-scheme: light)" 
      accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: logo

  globaltoc_collapse: true
  features:
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    # - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
extra:
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, undefined]
  generator: false
  version: !ENV [LATEST_VERSION, development]
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
plugins: 
  - search
  - social
  - minify:
      minify_html: true

markdown_extensions: 
  - abbr
  - admonition
  - def_list
  - toc:
      permalink: true
      title: Contents
      toc_depth: 4
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      #pygments_style: sphinx
  - pymdownx.superfences 
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - meta

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js

extra_css:
  - custom.css

nav:
  - Home: README.md
  - Getting Started: getting_started.md
  - Tutorials:
    - Basic Usage: tutorials/basic.md
    - External Functions: tutorials/external_functions.md
    - Checkpointing: tutorials/checkpointing.md
    - Higher-Order Derivatives: tutorials/higher_order.md
    - Handling Discontinuities: tutorials/smoothed_math.md
  - Reference:
    - Headers and Namespaces: ref/headers.md
    - AD Mode Interface: ref/interface.md
    - Forward Mode Type FReal: ref/freal.md
    - Adjoint Mode Type AReal: ref/areal.md
    - Global Functions: ref/global.md
    - Mathematical Operations: ref/math.md
    - Complex: ref/complex.md
    - Smoothed Mathematical Functions: ref/smooth-math.md
    - Expressions: ref/expressions.md
    - Tape: ref/tape.md
    - CheckpointCallback: ref/chkpt_cb.md
    - Exceptions: ref/exceptions.md
    - Version Information: ref/version.md
  - Examples: examples.md
  - AD Background:  aad.md
  - QuantLib Integration: quantlib.md
  - About: about.md