name: Build and test
on: [push, pull_request]
jobs:
  build-gcc-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install"
    - name: Build
      run: |
        cd build
        cmake --build . -- -j2
    - name: Test
      run: |
        cd build
        ctest --no-compress-output --output-on-failure -T Test -j 2
    - name: Install
      run: |
        cd build
        cmake --install .
    - name: Installation Test
      run: |
        mkdir installtest
        cd installtest
        cmake ../samples -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/install" 
        cmake --build .
  build-clang-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
    - name: Build
      run: |
        cd build
        cmake --build . -- -j2
    - name: Test
      run: |
        cd build
        ctest --no-compress-output --output-on-failure -T Test -j 2
  build-msvc:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX="$env:GITHUB_WORKSPACE/install"
    - name: Build Release
      run: |
        cd build
        cmake --build . --config Release
    - name: Build Debug
      run: |
        cd build
        cmake --build . --config Debug
    - name: Test Release
      run: |
        cd build
        ctest --no-compress-output --output-on-failure -T Test -C Release -j 2
    - name: Test Debug
      run: |
        cd build
        ctest --no-compress-output --output-on-failure -T Test -C Debug -j 2
    - name: Install
      run: |
        cd build
        cmake --install . --config Debug
        cmake --install . --config Release
    - name: Installation Test
      run: |
        mkdir installtest
        cd installtest
        cmake ..\\samples -DCMAKE_PREFIX_PATH="$env:GITHUB_WORKSPACE/install"
        cmake --build . --config Release
        cmake --build . --config Debug
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install" 
    - name: Build
      run: |
        cd build
        cmake --build . -- -j3
    - name: Test
      run: |
        cd build
        ctest --no-compress-output --output-on-failure -T Test -j 3
    - name: Install
      run: |
        cd build
        cmake --install .
    - name: Installation Test
      run: |
        mkdir installtest
        cd installtest
        cmake ../samples -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/install"  
        cmake --build .