name: Documentation
on: [push, pull_request]
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-science dvisvgm preview-latex-style
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DXAD_BUILD_DOCS=ON -DXAD_DOCS_ONLY=ON
          cmake --build . --target documentation
          rm -f doc/html/.buildinfo

      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: build/doc/html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/doc/html
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          dry-run: ${{ github.ref != 'refs/heads/main' }}  # dry run if not on main branch
          
